import Providers from "../components/Providers";

export const metadata = {
  title: "Wanderlyn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Porter+Sans+Block&display=swap" 
        rel="stylesheet"/>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
           rel="stylesheet"
          />

      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
